### ISSUE TITLE
chore: Enable Extra Key-Value Pair Configuration in YML to add extra context to AI 

### ISSUE THREAD

**Issue by soorya-u** [puneeth072003/CODESOURCERER#49]
## TODO

- YML Configuration should be able to receive any number of key value pair values under the key of `extras`. These key value pair can be fed to AI to produce more desirable Tests.

> For simplicity purpose, let the values be of type `string`

## Current Config

```yml
configuration:
  test-directory: "tests/"
  comments: "on"
  testing-branch: "main"
  testing-framework: "pytest"
  water-mark: "on"

environment:
  python-version: "3.10"

caching:
  enabled: false
  redis-caching: "off"
```

## Updated Config

```yml
configuration:
  test-directory: "tests/"
  comments: "on"
  testing-branch: "main"
  testing-framework: "pytest"
  water-mark: "on"

environment:
  python-version: "3.10"

caching:
  enabled: false
  redis-caching: "off"

extras:
  indent-type: "space"
  indent-size: "2"
  trailing-comma: "on"
  ...
  
```
